blank_issues_enabled: false
contact_links:
  - name: Help & support on Discord (soon)
    url: https://discord.gg
    about: We don't accept support requests on the issue tracker. Please try asking on Discord instead.
  - name: Help & support on forums (soon)
    url: https://google.com
    about: We don't accept support requests on the issue tracker. Please try asking on forums instead.
  - name: Documentation
    url: https://pocketobsidian.github.io/docs
    about: PocketObsidian documentation
